---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    username: AgAuAJx3MvEhNH+t5B6gSMht70VG2wv9MBnhuLerLFz8PBvOchDx3+817egKGuzn0t6ZvhaPHLxWX6heg6pbcIu+dcZow61rpmegvbHt4GztxC8uNvTYSq3Wjxmt/WguthC6VhqE/F+lfDMjPZqs4okc2RvXJJoiI01pp6esF4BU2MYrZQnNNqoenwcj8E9tCRtIEf0UVDwScOMFUlL3Yy9fp3Z29djpmVUlDJWmV+Op3quYEenRUPHVMxj9I7bP2RmQaDWVz+uo68ib6ozSjYSGgebQhxuwTk6U60dwVFjcOrKfMXsRyVvQzfKvJdbZ1jzzkE+klC3VZjE6iz53W9AMlsm9sTvAu76lZ2p2Z+XUwL5o4AqFMGfSJHg02w+uRqB24qFU/D6s7XfHM76w9oPrDO6ukYaSmSv7XtynUZ1nM9kAjoMK4zFyWtFYVw+5bHDI8OQAuPsxy23LuyPri9+NzjAMCc49M/8jcCa0rtHEffQQFVoWXlkySJv7y/vd/okS3lYsPwlpayGctzFhwP4WWstxeY5HOPVX7XBa4POMYLZttqdlL0z+e6AevuZjGzX1x+9Y2IdM3T+74XCVehuDeDbNMMFgh/8O7X5aFaYQQBx1aochKizKp4wWM3MF5w/zYAeCLUUaO8+TfPFayBSA5VuJEBmlFYFhy6qdfZEba/6V5UVxIiI3kCjvrpE6OMWivL3CHPbcTuFi
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
