name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run tfsec - Terraform Security Scanner
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Build Docker Image
        run: docker build -t anjali-app:latest .

      - name: Run Trivy - Docker Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'anjali-app:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
      - name: Apply Sealed Secret to Cluster
        run: kubectl apply --validate=false -f sealedsecret.yaml

