apply-sealed-secrets:
  name: Apply Sealed Secrets
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubeseal
      run: |
        wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.23.0/kubeseal-linux-amd64 -O kubeseal
        chmod +x kubeseal
        sudo mv kubeseal /usr/local/bin/

    - name: Setup kubeconfig file
      run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

    - name: Apply Sealed Secret
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      run: kubectl apply -f sealed-secret.yaml
